const PRODUCTS = [
  {
    "id": 1,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "6195 R",
    "name": "John Deere 6195 R",
    "year": 2014,
    "hours": 5006,
    "hp": 422,
    "price": 55200,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/images/77725b08-0d4b-43fc-95d0-2a720b39fb82.jpg",
    "badge": null
  },
  {
    "id": 2,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "7R 330",
    "name": "John Deere 7R 330",
    "year": 2022,
    "hours": 1924,
    "hp": 147,
    "price": 203400,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/images/604b35ba-24bd-44ec-a6f5-9403b5ad7032.jpg",
    "badge": null
  },
  {
    "id": 3,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "6R 250",
    "name": "John Deere 6R 250",
    "year": 2017,
    "hours": 4311,
    "hp": 110,
    "price": 50600,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/images/bdd7996a-2f76-428e-8f3f-3cb1382f842b.jpg",
    "badge": null
  },
  {
    "id": 4,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "6230 R",
    "name": "John Deere 6230 R",
    "year": 2022,
    "hours": 7373,
    "hp": 382,
    "price": 78100,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/images/8150a4f5-bb85-4ef1-a8ab-301f5b3edb55.jpg",
    "badge": null
  },
  {
    "id": 5,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "6R 175",
    "name": "John Deere 6R 175",
    "year": 2014,
    "hours": 3115,
    "hp": 237,
    "price": 238200,
    "country": "Poland",
    "image": "https://ik.imagekit.io/efarm/images/d224d0b6-9285-4aa6-9b44-277360a97c42.jpg",
    "badge": null
  },
  {
    "id": 6,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "8600",
    "name": "John Deere 8600",
    "year": 2019,
    "hours": 2174,
    "hp": 174,
    "price": 82400,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/images/5bf58f80-eed6-4ebb-bd75-ef51d15a6289.jpg",
    "badge": null
  },
  {
    "id": 7,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "7R 350",
    "name": "John Deere 7R 350",
    "year": 2019,
    "hours": 4833,
    "hp": 278,
    "price": 248200,
    "country": "France",
    "image": "https://ik.imagekit.io/efarm/images/12105f45-06bf-413d-a026-af923c0478e4.jpg",
    "badge": null
  },
  {
    "id": 8,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "8R 310",
    "name": "John Deere 8R 310",
    "year": 2020,
    "hours": 1791,
    "hp": 369,
    "price": 58700,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/images/d7f2c05c-236a-4a1d-9f71-7fbc9fd4fa61.jpg",
    "badge": null
  },
  {
    "id": 9,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "7R 290",
    "name": "John Deere 7R 290",
    "year": 2019,
    "hours": 3650,
    "hp": 416,
    "price": 188100,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/images/930821c9-1818-424a-a8b3-eb4d8eb6b9f2.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 10,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "7R 310",
    "name": "John Deere 7R 310",
    "year": 2018,
    "hours": 1807,
    "hp": 211,
    "price": 228700,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/images/89512ab0-f27e-43c9-ab84-3b9b5ae943f5.jpg",
    "badge": null
  },
  {
    "id": 11,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "6215 R",
    "name": "John Deere 6215 R",
    "year": 2021,
    "hours": 6477,
    "hp": 289,
    "price": 98900,
    "country": "Belgium",
    "image": "https://ik.imagekit.io/efarm/images/a0ada3ef-0feb-4a79-a14f-9b83020cd139.jpg",
    "badge": null
  },
  {
    "id": 12,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "6155 R",
    "name": "John Deere 6155 R",
    "year": 2018,
    "hours": 1669,
    "hp": 202,
    "price": 201700,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/images/5f727535-6660-4883-9c82-e2146794a8c6.jpg",
    "badge": null
  },
  {
    "id": 13,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "John Deere",
    "model": "6250 R",
    "name": "John Deere 6250 R",
    "year": 2017,
    "hours": 3177,
    "hp": 368,
    "price": 217100,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/images/a76fe002-1062-4b80-aeb2-4ce85052942f.jpg",
    "badge": null
  },
  {
    "id": 14,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Fendt",
    "model": "516 Vario",
    "name": "Fendt 516 Vario",
    "year": 2022,
    "hours": 4098,
    "hp": 422,
    "price": 206400,
    "country": "Italy",
    "image": "https://ik.imagekit.io/efarm/images/87391ee0-4434-492c-a706-a7e44799dbd8.jpg",
    "badge": null
  },
  {
    "id": 15,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Fendt",
    "model": "828 Vario Profi Plus",
    "name": "Fendt 828 Vario Profi Plus",
    "year": 2014,
    "hours": 5668,
    "hp": 123,
    "price": 86000,
    "country": "Poland",
    "image": "https://ik.imagekit.io/efarm/images/055758b2-5f4b-4b09-8567-a42d1b3d67c0.jpg",
    "badge": null
  },
  {
    "id": 16,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Fendt",
    "model": "724 Vario Power",
    "name": "Fendt 724 Vario Power",
    "year": 2019,
    "hours": 3983,
    "hp": 203,
    "price": 174700,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/images/fe2a3565-36ac-484e-91aa-54df1aca6731.jpg",
    "badge": null
  },
  {
    "id": 17,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Fendt",
    "model": "313 Vario Power",
    "name": "Fendt 313 Vario Power",
    "year": 2016,
    "hours": 4839,
    "hp": 424,
    "price": 146300,
    "country": "Belgium",
    "image": "https://ik.imagekit.io/efarm/images/bc21c9a5-1649-4df5-ac85-39f9a5846b0d.jpg",
    "badge": null
  },
  {
    "id": 18,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Fendt",
    "model": "724 Vario Profi",
    "name": "Fendt 724 Vario Profi",
    "year": 2018,
    "hours": 7519,
    "hp": 382,
    "price": 167300,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/images/a191a6ed-3440-42bd-afca-f5bdc5b38030.jpg",
    "badge": null
  },
  {
    "id": 19,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "New Holland",
    "model": "T7.245",
    "name": "New Holland T7.245",
    "year": 2022,
    "hours": 8585,
    "hp": 207,
    "price": 62300,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/images/0622fe9d-b82d-493d-b766-002a6c350cfc.jpg",
    "badge": null
  },
  {
    "id": 20,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "New Holland",
    "model": "T7.315",
    "name": "New Holland T7.315",
    "year": 2016,
    "hours": 7416,
    "hp": 151,
    "price": 66100,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/images/31eea827-c8d0-4201-aa5e-ec83bf600e5a.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 21,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "New Holland",
    "model": "T7.250",
    "name": "New Holland T7.250",
    "year": 2021,
    "hours": 9169,
    "hp": 290,
    "price": 182200,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/images/391634d7-f22f-4f9c-85a6-382d850c6347.jpg",
    "badge": null
  },
  {
    "id": 22,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "New Holland",
    "model": "T6.180",
    "name": "New Holland T6.180",
    "year": 2015,
    "hours": 9297,
    "hp": 100,
    "price": 204300,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/images/1d693d5d-5711-4ae4-a264-3e67f804a56e.jpg",
    "badge": null
  },
  {
    "id": 23,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "New Holland",
    "model": "T7.270",
    "name": "New Holland T7.270",
    "year": 2018,
    "hours": 7623,
    "hp": 269,
    "price": 55200,
    "country": "Belgium",
    "image": "https://ik.imagekit.io/efarm/images/77668617-b087-4b83-9809-a0f05c90f78f.jpg",
    "badge": null
  },
  {
    "id": 24,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Massey Ferguson",
    "model": "8670 Dyna-VT",
    "name": "Massey Ferguson 8670 Dyna-VT",
    "year": 2016,
    "hours": 8817,
    "hp": 229,
    "price": 157200,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/images/a58e3faa-c638-4f00-9de3-09cdfec81427.jpg",
    "badge": null
  },
  {
    "id": 25,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Massey Ferguson",
    "model": "6614",
    "name": "Massey Ferguson 6614",
    "year": 2022,
    "hours": 3758,
    "hp": 247,
    "price": 246600,
    "country": "Belgium",
    "image": "https://ik.imagekit.io/efarm/images/c66806fa-b901-4f29-8378-0553aa9b49c5.jpg",
    "badge": null
  },
  {
    "id": 26,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Massey Ferguson",
    "model": "7719 Dyna-VT",
    "name": "Massey Ferguson 7719 Dyna-VT",
    "year": 2022,
    "hours": 509,
    "hp": 177,
    "price": 167400,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/images/9c6bd364-a0e5-4dd2-aec0-0d246f8b80ae.jpg",
    "badge": null
  },
  {
    "id": 27,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Claas",
    "model": "Arion 650 CMATIC",
    "name": "Claas Arion 650 CMATIC",
    "year": 2019,
    "hours": 5538,
    "hp": 104,
    "price": 55300,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/images/0490b6f2-c5e2-442c-9425-13284d411c59.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 28,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Claas",
    "model": "Axion 960 CMATIC",
    "name": "Claas Axion 960 CMATIC",
    "year": 2015,
    "hours": 8462,
    "hp": 385,
    "price": 46600,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/images/3f5ba905-bd43-482b-a6d5-1eef927d7e4a.jpg",
    "badge": null
  },
  {
    "id": 29,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Claas",
    "model": "Axion 870",
    "name": "Claas Axion 870",
    "year": 2016,
    "hours": 2603,
    "hp": 367,
    "price": 226800,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/images/cf116c1e-4b5c-44af-823a-c91690215390.jpg",
    "badge": null
  },
  {
    "id": 30,
    "category": "tractors",
    "categoryLabel": "Tractors",
    "brand": "Claas",
    "model": "Arion 660",
    "name": "Claas Arion 660",
    "year": 2022,
    "hours": 7432,
    "hp": 179,
    "price": 95500,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/images/4657c9ab-7dc8-44ae-8658-98b68ffcc0da.jpg",
    "badge": null
  },
  {
    "id": 31,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Claas",
    "model": "Lexion 770",
    "name": "Claas Lexion 770",
    "year": 2017,
    "hours": 5607,
    "hp": 653,
    "price": 245800,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/92/A_combine_harvester_parked_in_a_field_-_geograph.org.uk_-_550647.jpg",
    "badge": null
  },
  {
    "id": 32,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Claas",
    "model": "Lexion 660",
    "name": "Claas Lexion 660",
    "year": 2021,
    "hours": 8979,
    "hp": 612,
    "price": 162900,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Combine_Harvester_at_Corston_Field_Farm_-_geograph.org.uk_-_956405.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 33,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Claas",
    "model": "Lexion 8700",
    "name": "Claas Lexion 8700",
    "year": 2019,
    "hours": 844,
    "hp": 395,
    "price": 81800,
    "country": "Austria",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Combine_Harvester_in_Action_-_geograph.org.uk_-_5096129.jpg",
    "badge": null
  },
  {
    "id": 34,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Claas",
    "model": "Lexion 6800",
    "name": "Claas Lexion 6800",
    "year": 2014,
    "hours": 1663,
    "hp": 581,
    "price": 122700,
    "country": "France",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Combine_Harvester_in_Field_-_geograph.org.uk_-_385537.jpg",
    "badge": null
  },
  {
    "id": 35,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "John Deere",
    "model": "S780",
    "name": "John Deere S780",
    "year": 2019,
    "hours": 1660,
    "hp": 296,
    "price": 290300,
    "country": "Ireland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Combine_harvester_-_geograph.org.uk_-_980749.jpg",
    "badge": null
  },
  {
    "id": 36,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "John Deere",
    "model": "S670",
    "name": "John Deere S670",
    "year": 2017,
    "hours": 9334,
    "hp": 622,
    "price": 192200,
    "country": "Belgium",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/55/Combine_harvester_cutting_wheat_field_-_geograph.org.uk_-_520759.jpg",
    "badge": null
  },
  {
    "id": 37,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "John Deere",
    "model": "T670",
    "name": "John Deere T670",
    "year": 2021,
    "hours": 4481,
    "hp": 572,
    "price": 216000,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Combine_harvester_in_Rape_Seed_field_-_geograph.org.uk_-_2074844.jpg/960px-Combine_harvester_in_Rape_Seed_field_-_geograph.org.uk_-_2074844.jpg",
    "badge": null
  },
  {
    "id": 38,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "John Deere",
    "model": "S760",
    "name": "John Deere S760",
    "year": 2015,
    "hours": 7562,
    "hp": 377,
    "price": 89700,
    "country": "Italy",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Combine_harvester_in_a_field_near_Balblair_-_geograph.org.uk_-_3206182.jpg/960px-Combine_harvester_in_a_field_near_Balblair_-_geograph.org.uk_-_3206182.jpg",
    "badge": null
  },
  {
    "id": 39,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Fendt",
    "model": "IDEAL 9T",
    "name": "Fendt IDEAL 9T",
    "year": 2014,
    "hours": 2112,
    "hp": 519,
    "price": 291400,
    "country": "France",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/92/A_combine_harvester_parked_in_a_field_-_geograph.org.uk_-_550647.jpg",
    "badge": null
  },
  {
    "id": 40,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Fendt",
    "model": "IDEAL 8T",
    "name": "Fendt IDEAL 8T",
    "year": 2015,
    "hours": 4573,
    "hp": 453,
    "price": 274900,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Combine_Harvester_at_Corston_Field_Farm_-_geograph.org.uk_-_956405.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 41,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Fendt",
    "model": "IDEAL 7",
    "name": "Fendt IDEAL 7",
    "year": 2020,
    "hours": 3506,
    "hp": 509,
    "price": 101700,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Combine_Harvester_in_Action_-_geograph.org.uk_-_5096129.jpg",
    "badge": null
  },
  {
    "id": 42,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Case IH",
    "model": "Axial-Flow 9250",
    "name": "Case IH Axial-Flow 9250",
    "year": 2022,
    "hours": 2104,
    "hp": 318,
    "price": 181200,
    "country": "France",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Combine_Harvester_in_Field_-_geograph.org.uk_-_385537.jpg",
    "badge": null
  },
  {
    "id": 43,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Case IH",
    "model": "Axial-Flow 8250",
    "name": "Case IH Axial-Flow 8250",
    "year": 2014,
    "hours": 2028,
    "hp": 556,
    "price": 284200,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Combine_harvester_-_geograph.org.uk_-_980749.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 44,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "New Holland",
    "model": "CX8.90",
    "name": "New Holland CX8.90",
    "year": 2017,
    "hours": 7070,
    "hp": 528,
    "price": 191200,
    "country": "France",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/55/Combine_harvester_cutting_wheat_field_-_geograph.org.uk_-_520759.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 45,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "New Holland",
    "model": "CR9.90",
    "name": "New Holland CR9.90",
    "year": 2018,
    "hours": 7954,
    "hp": 281,
    "price": 167300,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Combine_harvester_in_Rape_Seed_field_-_geograph.org.uk_-_2074844.jpg/960px-Combine_harvester_in_Rape_Seed_field_-_geograph.org.uk_-_2074844.jpg",
    "badge": null
  },
  {
    "id": 46,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "New Holland",
    "model": "CX8.80",
    "name": "New Holland CX8.80",
    "year": 2021,
    "hours": 3036,
    "hp": 564,
    "price": 238500,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Combine_harvester_in_a_field_near_Balblair_-_geograph.org.uk_-_3206182.jpg/960px-Combine_harvester_in_a_field_near_Balblair_-_geograph.org.uk_-_3206182.jpg",
    "badge": null
  },
  {
    "id": 47,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Claas",
    "model": "Lexion 770",
    "name": "Claas Lexion 770",
    "year": 2022,
    "hours": 1498,
    "hp": 309,
    "price": 216800,
    "country": "Italy",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/92/A_combine_harvester_parked_in_a_field_-_geograph.org.uk_-_550647.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 48,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Claas",
    "model": "Lexion 660",
    "name": "Claas Lexion 660",
    "year": 2022,
    "hours": 9201,
    "hp": 579,
    "price": 190000,
    "country": "Belgium",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Combine_Harvester_at_Corston_Field_Farm_-_geograph.org.uk_-_956405.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 49,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Claas",
    "model": "Lexion 8700",
    "name": "Claas Lexion 8700",
    "year": 2016,
    "hours": 1622,
    "hp": 540,
    "price": 86000,
    "country": "Austria",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Combine_Harvester_in_Action_-_geograph.org.uk_-_5096129.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 50,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Claas",
    "model": "Lexion 6800",
    "name": "Claas Lexion 6800",
    "year": 2015,
    "hours": 4533,
    "hp": 400,
    "price": 170800,
    "country": "Austria",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Combine_Harvester_in_Field_-_geograph.org.uk_-_385537.jpg",
    "badge": null
  },
  {
    "id": 51,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "John Deere",
    "model": "S780",
    "name": "John Deere S780",
    "year": 2020,
    "hours": 9065,
    "hp": 597,
    "price": 86500,
    "country": "Italy",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Combine_harvester_-_geograph.org.uk_-_980749.jpg",
    "badge": null
  },
  {
    "id": 52,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "John Deere",
    "model": "S670",
    "name": "John Deere S670",
    "year": 2019,
    "hours": 4410,
    "hp": 384,
    "price": 240600,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/55/Combine_harvester_cutting_wheat_field_-_geograph.org.uk_-_520759.jpg",
    "badge": null
  },
  {
    "id": 53,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "John Deere",
    "model": "T670",
    "name": "John Deere T670",
    "year": 2018,
    "hours": 7991,
    "hp": 623,
    "price": 234200,
    "country": "Italy",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Combine_harvester_in_Rape_Seed_field_-_geograph.org.uk_-_2074844.jpg/960px-Combine_harvester_in_Rape_Seed_field_-_geograph.org.uk_-_2074844.jpg",
    "badge": null
  },
  {
    "id": 54,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "John Deere",
    "model": "S760",
    "name": "John Deere S760",
    "year": 2021,
    "hours": 2138,
    "hp": 317,
    "price": 67400,
    "country": "Germany",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Combine_harvester_in_a_field_near_Balblair_-_geograph.org.uk_-_3206182.jpg/960px-Combine_harvester_in_a_field_near_Balblair_-_geograph.org.uk_-_3206182.jpg",
    "badge": null
  },
  {
    "id": 55,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Fendt",
    "model": "IDEAL 9T",
    "name": "Fendt IDEAL 9T",
    "year": 2016,
    "hours": 6218,
    "hp": 539,
    "price": 134500,
    "country": "Germany",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/92/A_combine_harvester_parked_in_a_field_-_geograph.org.uk_-_550647.jpg",
    "badge": null
  },
  {
    "id": 56,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Fendt",
    "model": "IDEAL 8T",
    "name": "Fendt IDEAL 8T",
    "year": 2016,
    "hours": 7679,
    "hp": 469,
    "price": 139700,
    "country": "Ireland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Combine_Harvester_at_Corston_Field_Farm_-_geograph.org.uk_-_956405.jpg",
    "badge": null
  },
  {
    "id": 57,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Fendt",
    "model": "IDEAL 7",
    "name": "Fendt IDEAL 7",
    "year": 2022,
    "hours": 628,
    "hp": 593,
    "price": 276600,
    "country": "Ireland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Combine_Harvester_in_Action_-_geograph.org.uk_-_5096129.jpg",
    "badge": null
  },
  {
    "id": 58,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Case IH",
    "model": "Axial-Flow 9250",
    "name": "Case IH Axial-Flow 9250",
    "year": 2016,
    "hours": 4833,
    "hp": 619,
    "price": 92200,
    "country": "Germany",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Combine_Harvester_in_Field_-_geograph.org.uk_-_385537.jpg",
    "badge": null
  },
  {
    "id": 59,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "Case IH",
    "model": "Axial-Flow 8250",
    "name": "Case IH Axial-Flow 8250",
    "year": 2018,
    "hours": 5116,
    "hp": 563,
    "price": 105700,
    "country": "Austria",
    "image": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Combine_harvester_-_geograph.org.uk_-_980749.jpg",
    "badge": null
  },
  {
    "id": 60,
    "category": "combine-harvesters",
    "categoryLabel": "Combine harvesters",
    "brand": "New Holland",
    "model": "CX8.90",
    "name": "New Holland CX8.90",
    "year": 2018,
    "hours": 8780,
    "hp": 455,
    "price": 118400,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/5/55/Combine_harvester_cutting_wheat_field_-_geograph.org.uk_-_520759.jpg",
    "badge": null
  },
  {
    "id": 61,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Claas",
    "model": "Variant 485",
    "name": "Claas Variant 485",
    "year": 2015,
    "hours": 7439,
    "hp": 176,
    "price": 16200,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Baler_operating_near_Pikendale_Plantation_-_geograph.org.uk_-_542422.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 62,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Claas",
    "model": "Rollant 454",
    "name": "Claas Rollant 454",
    "year": 2018,
    "hours": 3147,
    "hp": 102,
    "price": 26600,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Baling_Machine_in_Billinge_-_geograph.org.uk_-_537938.jpg",
    "badge": null
  },
  {
    "id": 63,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Claas",
    "model": "Quadrant 5300",
    "name": "Claas Quadrant 5300",
    "year": 2015,
    "hours": 1732,
    "hp": 114,
    "price": 10800,
    "country": "Belgium",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/90/John_Deere_328_square_baler_d.jpg",
    "badge": null
  },
  {
    "id": 64,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Kuhn",
    "model": "VB 3160",
    "name": "Kuhn VB 3160",
    "year": 2023,
    "hours": 2926,
    "hp": 166,
    "price": 57900,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Round_baler_3061.jpg/960px-Round_baler_3061.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 65,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Kuhn",
    "model": "LSB 1290 iD",
    "name": "Kuhn LSB 1290 iD",
    "year": 2014,
    "hours": 6362,
    "hp": 99,
    "price": 57300,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Round_baler_3070.jpg/960px-Round_baler_3070.jpg",
    "badge": null
  },
  {
    "id": 66,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Krone",
    "model": "Comprima V180",
    "name": "Krone Comprima V180",
    "year": 2019,
    "hours": 7158,
    "hp": 145,
    "price": 23000,
    "country": "Austria",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Sgorbati_baler_in_Bulgaria_01.jpg/960px-Sgorbati_baler_in_Bulgaria_01.jpg",
    "badge": null
  },
  {
    "id": 67,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Krone",
    "model": "BigPack 1290 HDP",
    "name": "Krone BigPack 1290 HDP",
    "year": 2016,
    "hours": 3400,
    "hp": 178,
    "price": 40500,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/81/Square_Baler_In_Action_Near_Poldar_Moss_-_geograph.org.uk_-_1444500.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 68,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "New Holland",
    "model": "Roll-Belt 150",
    "name": "New Holland Roll-Belt 150",
    "year": 2020,
    "hours": 4565,
    "hp": 154,
    "price": 53000,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Tractor_with_square_baler_in_Sweden.jpg/960px-Tractor_with_square_baler_in_Sweden.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 69,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "New Holland",
    "model": "BigBaler 1290",
    "name": "New Holland BigBaler 1290",
    "year": 2020,
    "hours": 1134,
    "hp": 149,
    "price": 23700,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Baler_operating_near_Pikendale_Plantation_-_geograph.org.uk_-_542422.jpg",
    "badge": null
  },
  {
    "id": 70,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "John Deere",
    "model": "V451M",
    "name": "John Deere V451M",
    "year": 2019,
    "hours": 5500,
    "hp": 164,
    "price": 69800,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Baling_Machine_in_Billinge_-_geograph.org.uk_-_537938.jpg",
    "badge": null
  },
  {
    "id": 71,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "John Deere",
    "model": "870 Premium",
    "name": "John Deere 870 Premium",
    "year": 2020,
    "hours": 5878,
    "hp": 144,
    "price": 34800,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/90/John_Deere_328_square_baler_d.jpg",
    "badge": null
  },
  {
    "id": 72,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Claas",
    "model": "Variant 485",
    "name": "Claas Variant 485",
    "year": 2019,
    "hours": 8846,
    "hp": 158,
    "price": 46100,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Round_baler_3061.jpg/960px-Round_baler_3061.jpg",
    "badge": null
  },
  {
    "id": 73,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Claas",
    "model": "Rollant 454",
    "name": "Claas Rollant 454",
    "year": 2014,
    "hours": 2389,
    "hp": 167,
    "price": 52900,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Round_baler_3070.jpg/960px-Round_baler_3070.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 74,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Claas",
    "model": "Quadrant 5300",
    "name": "Claas Quadrant 5300",
    "year": 2015,
    "hours": 7619,
    "hp": 93,
    "price": 14500,
    "country": "Italy",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Sgorbati_baler_in_Bulgaria_01.jpg/960px-Sgorbati_baler_in_Bulgaria_01.jpg",
    "badge": null
  },
  {
    "id": 75,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Kuhn",
    "model": "VB 3160",
    "name": "Kuhn VB 3160",
    "year": 2023,
    "hours": 8879,
    "hp": 100,
    "price": 66700,
    "country": "Germany",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/81/Square_Baler_In_Action_Near_Poldar_Moss_-_geograph.org.uk_-_1444500.jpg",
    "badge": null
  },
  {
    "id": 76,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Kuhn",
    "model": "LSB 1290 iD",
    "name": "Kuhn LSB 1290 iD",
    "year": 2018,
    "hours": 1227,
    "hp": 133,
    "price": 34400,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Tractor_with_square_baler_in_Sweden.jpg/960px-Tractor_with_square_baler_in_Sweden.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 77,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Krone",
    "model": "Comprima V180",
    "name": "Krone Comprima V180",
    "year": 2019,
    "hours": 7566,
    "hp": 178,
    "price": 35300,
    "country": "Germany",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Baler_operating_near_Pikendale_Plantation_-_geograph.org.uk_-_542422.jpg",
    "badge": null
  },
  {
    "id": 78,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Krone",
    "model": "BigPack 1290 HDP",
    "name": "Krone BigPack 1290 HDP",
    "year": 2023,
    "hours": 5643,
    "hp": 177,
    "price": 52800,
    "country": "Germany",
    "image": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Baling_Machine_in_Billinge_-_geograph.org.uk_-_537938.jpg",
    "badge": null
  },
  {
    "id": 79,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "New Holland",
    "model": "Roll-Belt 150",
    "name": "New Holland Roll-Belt 150",
    "year": 2018,
    "hours": 7191,
    "hp": 98,
    "price": 76000,
    "country": "Italy",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/90/John_Deere_328_square_baler_d.jpg",
    "badge": null
  },
  {
    "id": 80,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "New Holland",
    "model": "BigBaler 1290",
    "name": "New Holland BigBaler 1290",
    "year": 2017,
    "hours": 7388,
    "hp": 97,
    "price": 26200,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Round_baler_3061.jpg/960px-Round_baler_3061.jpg",
    "badge": null
  },
  {
    "id": 81,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "John Deere",
    "model": "V451M",
    "name": "John Deere V451M",
    "year": 2023,
    "hours": 5430,
    "hp": 175,
    "price": 32300,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Round_baler_3070.jpg/960px-Round_baler_3070.jpg",
    "badge": null
  },
  {
    "id": 82,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "John Deere",
    "model": "870 Premium",
    "name": "John Deere 870 Premium",
    "year": 2018,
    "hours": 3943,
    "hp": 60,
    "price": 49300,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Sgorbati_baler_in_Bulgaria_01.jpg/960px-Sgorbati_baler_in_Bulgaria_01.jpg",
    "badge": null
  },
  {
    "id": 83,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Claas",
    "model": "Variant 485",
    "name": "Claas Variant 485",
    "year": 2021,
    "hours": 7738,
    "hp": 137,
    "price": 51700,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/81/Square_Baler_In_Action_Near_Poldar_Moss_-_geograph.org.uk_-_1444500.jpg",
    "badge": null
  },
  {
    "id": 84,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Claas",
    "model": "Rollant 454",
    "name": "Claas Rollant 454",
    "year": 2016,
    "hours": 1889,
    "hp": 125,
    "price": 71500,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Tractor_with_square_baler_in_Sweden.jpg/960px-Tractor_with_square_baler_in_Sweden.jpg",
    "badge": null
  },
  {
    "id": 85,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Claas",
    "model": "Quadrant 5300",
    "name": "Claas Quadrant 5300",
    "year": 2015,
    "hours": 4348,
    "hp": 141,
    "price": 53400,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Baler_operating_near_Pikendale_Plantation_-_geograph.org.uk_-_542422.jpg",
    "badge": null
  },
  {
    "id": 86,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Kuhn",
    "model": "VB 3160",
    "name": "Kuhn VB 3160",
    "year": 2014,
    "hours": 1257,
    "hp": 85,
    "price": 28800,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Baling_Machine_in_Billinge_-_geograph.org.uk_-_537938.jpg",
    "badge": null
  },
  {
    "id": 87,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Kuhn",
    "model": "LSB 1290 iD",
    "name": "Kuhn LSB 1290 iD",
    "year": 2021,
    "hours": 7290,
    "hp": 138,
    "price": 19000,
    "country": "Austria",
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/90/John_Deere_328_square_baler_d.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 88,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Krone",
    "model": "Comprima V180",
    "name": "Krone Comprima V180",
    "year": 2021,
    "hours": 7047,
    "hp": 149,
    "price": 59800,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Round_baler_3061.jpg/960px-Round_baler_3061.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 89,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "Krone",
    "model": "BigPack 1290 HDP",
    "name": "Krone BigPack 1290 HDP",
    "year": 2015,
    "hours": 7465,
    "hp": 148,
    "price": 10200,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Round_baler_3070.jpg/960px-Round_baler_3070.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 90,
    "category": "balers",
    "categoryLabel": "Balers",
    "brand": "New Holland",
    "model": "Roll-Belt 150",
    "name": "New Holland Roll-Belt 150",
    "year": 2021,
    "hours": 1322,
    "hp": 149,
    "price": 77400,
    "country": "Ireland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Sgorbati_baler_in_Bulgaria_01.jpg/960px-Sgorbati_baler_in_Bulgaria_01.jpg",
    "badge": null
  },
  {
    "id": 91,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Manitou",
    "model": "MLT 741-140",
    "name": "Manitou MLT 741-140",
    "year": 2016,
    "hours": 8112,
    "hp": 90,
    "price": 77800,
    "country": "Ireland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Bobcat_telehandler_in_Germany.jpg/960px-Bobcat_telehandler_in_Germany.jpg",
    "badge": null
  },
  {
    "id": 92,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Manitou",
    "model": "MLT 840-137",
    "name": "Manitou MLT 840-137",
    "year": 2021,
    "hours": 8770,
    "hp": 151,
    "price": 59600,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Farm_telehandler_-_geograph.org.uk_-_2103129.jpg/960px-Farm_telehandler_-_geograph.org.uk_-_2103129.jpg",
    "badge": null
  },
  {
    "id": 93,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Manitou",
    "model": "MT 1440",
    "name": "Manitou MT 1440",
    "year": 2016,
    "hours": 8277,
    "hp": 145,
    "price": 76400,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/JCB_Telehandler_-_geograph.org.uk_-_6663199.jpg/960px-JCB_Telehandler_-_geograph.org.uk_-_6663199.jpg",
    "badge": null
  },
  {
    "id": 94,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "JCB",
    "model": "536-70",
    "name": "JCB 536-70",
    "year": 2022,
    "hours": 8439,
    "hp": 106,
    "price": 54300,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/MERLO_Panoramic_P34.7_medium_lift_telehandler_at_IndAgra_Farm_Romexpo_2010.JPG/960px-MERLO_Panoramic_P34.7_medium_lift_telehandler_at_IndAgra_Farm_Romexpo_2010.JPG",
    "badge": null
  },
  {
    "id": 95,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "JCB",
    "model": "542-70 Agri",
    "name": "JCB 542-70 Agri",
    "year": 2017,
    "hours": 4951,
    "hp": 84,
    "price": 55400,
    "country": "Italy",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Telehandler_and_tractor_-_geograph.org.uk_-_6328352.jpg/960px-Telehandler_and_tractor_-_geograph.org.uk_-_6328352.jpg",
    "badge": null
  },
  {
    "id": 96,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Merlo",
    "model": "TF 42.7",
    "name": "Merlo TF 42.7",
    "year": 2016,
    "hours": 2971,
    "hp": 144,
    "price": 28600,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Telescopic_handler2.jpg/960px-Telescopic_handler2.jpg",
    "badge": null
  },
  {
    "id": 97,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Merlo",
    "model": "P40.17",
    "name": "Merlo P40.17",
    "year": 2015,
    "hours": 7297,
    "hp": 94,
    "price": 46000,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Agricultural_handler%2C_Knocknahorn_-_geograph.org.uk_-_6405426.jpg/960px-Agricultural_handler%2C_Knocknahorn_-_geograph.org.uk_-_6405426.jpg",
    "badge": null
  },
  {
    "id": 98,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Claas",
    "model": "Scorpion 756",
    "name": "Claas Scorpion 756",
    "year": 2014,
    "hours": 3888,
    "hp": 134,
    "price": 72500,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Telehandler%2C_Noss_Marina_-_geograph.org.uk_-_6612574.jpg/960px-Telehandler%2C_Noss_Marina_-_geograph.org.uk_-_6612574.jpg",
    "badge": null
  },
  {
    "id": 99,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Claas",
    "model": "Scorpion 741",
    "name": "Claas Scorpion 741",
    "year": 2014,
    "hours": 6732,
    "hp": 173,
    "price": 94600,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Bobcat_telehandler_in_Germany.jpg/960px-Bobcat_telehandler_in_Germany.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 100,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "New Holland",
    "model": "TH 7.42",
    "name": "New Holland TH 7.42",
    "year": 2020,
    "hours": 7365,
    "hp": 120,
    "price": 57100,
    "country": "Ireland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Farm_telehandler_-_geograph.org.uk_-_2103129.jpg/960px-Farm_telehandler_-_geograph.org.uk_-_2103129.jpg",
    "badge": null
  },
  {
    "id": 101,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "New Holland",
    "model": "LM 7.42",
    "name": "New Holland LM 7.42",
    "year": 2017,
    "hours": 8499,
    "hp": 144,
    "price": 97100,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/JCB_Telehandler_-_geograph.org.uk_-_6663199.jpg/960px-JCB_Telehandler_-_geograph.org.uk_-_6663199.jpg",
    "badge": null
  },
  {
    "id": 102,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Manitou",
    "model": "MLT 741-140",
    "name": "Manitou MLT 741-140",
    "year": 2020,
    "hours": 6007,
    "hp": 137,
    "price": 21800,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/MERLO_Panoramic_P34.7_medium_lift_telehandler_at_IndAgra_Farm_Romexpo_2010.JPG/960px-MERLO_Panoramic_P34.7_medium_lift_telehandler_at_IndAgra_Farm_Romexpo_2010.JPG",
    "badge": null
  },
  {
    "id": 103,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Manitou",
    "model": "MLT 840-137",
    "name": "Manitou MLT 840-137",
    "year": 2023,
    "hours": 9251,
    "hp": 134,
    "price": 34700,
    "country": "France",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Telehandler_and_tractor_-_geograph.org.uk_-_6328352.jpg/960px-Telehandler_and_tractor_-_geograph.org.uk_-_6328352.jpg",
    "badge": null
  },
  {
    "id": 104,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Manitou",
    "model": "MT 1440",
    "name": "Manitou MT 1440",
    "year": 2014,
    "hours": 1875,
    "hp": 150,
    "price": 92000,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Telescopic_handler2.jpg/960px-Telescopic_handler2.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 105,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "JCB",
    "model": "536-70",
    "name": "JCB 536-70",
    "year": 2014,
    "hours": 4762,
    "hp": 134,
    "price": 41800,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Agricultural_handler%2C_Knocknahorn_-_geograph.org.uk_-_6405426.jpg/960px-Agricultural_handler%2C_Knocknahorn_-_geograph.org.uk_-_6405426.jpg",
    "badge": null
  },
  {
    "id": 106,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "JCB",
    "model": "542-70 Agri",
    "name": "JCB 542-70 Agri",
    "year": 2019,
    "hours": 6711,
    "hp": 133,
    "price": 60800,
    "country": "Spain",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Telehandler%2C_Noss_Marina_-_geograph.org.uk_-_6612574.jpg/960px-Telehandler%2C_Noss_Marina_-_geograph.org.uk_-_6612574.jpg",
    "badge": null
  },
  {
    "id": 107,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Merlo",
    "model": "TF 42.7",
    "name": "Merlo TF 42.7",
    "year": 2015,
    "hours": 8205,
    "hp": 128,
    "price": 51100,
    "country": "France",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Bobcat_telehandler_in_Germany.jpg/960px-Bobcat_telehandler_in_Germany.jpg",
    "badge": null
  },
  {
    "id": 108,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Merlo",
    "model": "P40.17",
    "name": "Merlo P40.17",
    "year": 2017,
    "hours": 1624,
    "hp": 81,
    "price": 63900,
    "country": "France",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Farm_telehandler_-_geograph.org.uk_-_2103129.jpg/960px-Farm_telehandler_-_geograph.org.uk_-_2103129.jpg",
    "badge": null
  },
  {
    "id": 109,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Claas",
    "model": "Scorpion 756",
    "name": "Claas Scorpion 756",
    "year": 2014,
    "hours": 2996,
    "hp": 106,
    "price": 44100,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/JCB_Telehandler_-_geograph.org.uk_-_6663199.jpg/960px-JCB_Telehandler_-_geograph.org.uk_-_6663199.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 110,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Claas",
    "model": "Scorpion 741",
    "name": "Claas Scorpion 741",
    "year": 2023,
    "hours": 4071,
    "hp": 160,
    "price": 33000,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/MERLO_Panoramic_P34.7_medium_lift_telehandler_at_IndAgra_Farm_Romexpo_2010.JPG/960px-MERLO_Panoramic_P34.7_medium_lift_telehandler_at_IndAgra_Farm_Romexpo_2010.JPG",
    "badge": null
  },
  {
    "id": 111,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "New Holland",
    "model": "TH 7.42",
    "name": "New Holland TH 7.42",
    "year": 2016,
    "hours": 2376,
    "hp": 173,
    "price": 66400,
    "country": "Belgium",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Telehandler_and_tractor_-_geograph.org.uk_-_6328352.jpg/960px-Telehandler_and_tractor_-_geograph.org.uk_-_6328352.jpg",
    "badge": null
  },
  {
    "id": 112,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "New Holland",
    "model": "LM 7.42",
    "name": "New Holland LM 7.42",
    "year": 2014,
    "hours": 5611,
    "hp": 88,
    "price": 93800,
    "country": "Austria",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Telescopic_handler2.jpg/960px-Telescopic_handler2.jpg",
    "badge": null
  },
  {
    "id": 113,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Manitou",
    "model": "MLT 741-140",
    "name": "Manitou MLT 741-140",
    "year": 2017,
    "hours": 1745,
    "hp": 123,
    "price": 70000,
    "country": "Austria",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Agricultural_handler%2C_Knocknahorn_-_geograph.org.uk_-_6405426.jpg/960px-Agricultural_handler%2C_Knocknahorn_-_geograph.org.uk_-_6405426.jpg",
    "badge": null
  },
  {
    "id": 114,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Manitou",
    "model": "MLT 840-137",
    "name": "Manitou MLT 840-137",
    "year": 2015,
    "hours": 5441,
    "hp": 155,
    "price": 49800,
    "country": "Austria",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Telehandler%2C_Noss_Marina_-_geograph.org.uk_-_6612574.jpg/960px-Telehandler%2C_Noss_Marina_-_geograph.org.uk_-_6612574.jpg",
    "badge": null
  },
  {
    "id": 115,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Manitou",
    "model": "MT 1440",
    "name": "Manitou MT 1440",
    "year": 2019,
    "hours": 9228,
    "hp": 147,
    "price": 23400,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Bobcat_telehandler_in_Germany.jpg/960px-Bobcat_telehandler_in_Germany.jpg",
    "badge": null
  },
  {
    "id": 116,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "JCB",
    "model": "536-70",
    "name": "JCB 536-70",
    "year": 2019,
    "hours": 707,
    "hp": 83,
    "price": 84300,
    "country": "Poland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Farm_telehandler_-_geograph.org.uk_-_2103129.jpg/960px-Farm_telehandler_-_geograph.org.uk_-_2103129.jpg",
    "badge": null
  },
  {
    "id": 117,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "JCB",
    "model": "542-70 Agri",
    "name": "JCB 542-70 Agri",
    "year": 2019,
    "hours": 8032,
    "hp": 88,
    "price": 74800,
    "country": "Belgium",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/JCB_Telehandler_-_geograph.org.uk_-_6663199.jpg/960px-JCB_Telehandler_-_geograph.org.uk_-_6663199.jpg",
    "badge": null
  },
  {
    "id": 118,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Merlo",
    "model": "TF 42.7",
    "name": "Merlo TF 42.7",
    "year": 2018,
    "hours": 9317,
    "hp": 168,
    "price": 86400,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/MERLO_Panoramic_P34.7_medium_lift_telehandler_at_IndAgra_Farm_Romexpo_2010.JPG/960px-MERLO_Panoramic_P34.7_medium_lift_telehandler_at_IndAgra_Farm_Romexpo_2010.JPG",
    "badge": null
  },
  {
    "id": 119,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Merlo",
    "model": "P40.17",
    "name": "Merlo P40.17",
    "year": 2018,
    "hours": 5780,
    "hp": 168,
    "price": 95700,
    "country": "Netherlands",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Telehandler_and_tractor_-_geograph.org.uk_-_6328352.jpg/960px-Telehandler_and_tractor_-_geograph.org.uk_-_6328352.jpg",
    "badge": null
  },
  {
    "id": 120,
    "category": "telehandlers",
    "categoryLabel": "Telehandlers",
    "brand": "Claas",
    "model": "Scorpion 756",
    "name": "Claas Scorpion 756",
    "year": 2021,
    "hours": 4495,
    "hp": 86,
    "price": 54600,
    "country": "Denmark",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Telescopic_handler2.jpg/960px-Telescopic_handler2.jpg",
    "badge": null
  },
  {
    "id": 121,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Kuhn",
    "model": "GMD 3125",
    "name": "Kuhn GMD 3125",
    "year": 2014,
    "hours": 8598,
    "hp": 73,
    "price": 14500,
    "country": "Italy",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 122,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Kuhn",
    "model": "FC 3125 TLR",
    "name": "Kuhn FC 3125 TLR",
    "year": 2018,
    "hours": 6076,
    "hp": 52,
    "price": 15100,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 123,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Krone",
    "model": "EasyCut B 950",
    "name": "Krone EasyCut B 950",
    "year": 2014,
    "hours": 8964,
    "hp": 60,
    "price": 21700,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 124,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Krone",
    "model": "EasyCut F 320 CV",
    "name": "Krone EasyCut F 320 CV",
    "year": 2022,
    "hours": 4437,
    "hp": 77,
    "price": 19500,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 125,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Claas",
    "model": "Disco 3600",
    "name": "Claas Disco 3600",
    "year": 2014,
    "hours": 2024,
    "hp": 87,
    "price": 18200,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 126,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Claas",
    "model": "Disco 8500",
    "name": "Claas Disco 8500",
    "year": 2023,
    "hours": 6546,
    "hp": 56,
    "price": 13500,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 127,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Pottinger",
    "model": "Novacat 352",
    "name": "Pottinger Novacat 352",
    "year": 2022,
    "hours": 5919,
    "hp": 69,
    "price": 17400,
    "country": "Italy",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 128,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Pottinger",
    "model": "Novacat 262",
    "name": "Pottinger Novacat 262",
    "year": 2018,
    "hours": 4277,
    "hp": 59,
    "price": 13500,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 129,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "New Holland",
    "model": "DiscCutter 313",
    "name": "New Holland DiscCutter 313",
    "year": 2022,
    "hours": 3533,
    "hp": 65,
    "price": 7400,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 130,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "New Holland",
    "model": "DiscCutter 442",
    "name": "New Holland DiscCutter 442",
    "year": 2023,
    "hours": 9095,
    "hp": 86,
    "price": 12600,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 131,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Kuhn",
    "model": "GMD 3125",
    "name": "Kuhn GMD 3125",
    "year": 2018,
    "hours": 4227,
    "hp": 37,
    "price": 9900,
    "country": "Italy",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 132,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Kuhn",
    "model": "FC 3125 TLR",
    "name": "Kuhn FC 3125 TLR",
    "year": 2022,
    "hours": 2573,
    "hp": 26,
    "price": 26700,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 133,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Krone",
    "model": "EasyCut B 950",
    "name": "Krone EasyCut B 950",
    "year": 2018,
    "hours": 2568,
    "hp": 31,
    "price": 21600,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 134,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Krone",
    "model": "EasyCut F 320 CV",
    "name": "Krone EasyCut F 320 CV",
    "year": 2018,
    "hours": 8190,
    "hp": 26,
    "price": 22300,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 135,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Claas",
    "model": "Disco 3600",
    "name": "Claas Disco 3600",
    "year": 2018,
    "hours": 8327,
    "hp": 48,
    "price": 5200,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 136,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Claas",
    "model": "Disco 8500",
    "name": "Claas Disco 8500",
    "year": 2015,
    "hours": 1378,
    "hp": 76,
    "price": 19600,
    "country": "Belgium",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 137,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Pottinger",
    "model": "Novacat 352",
    "name": "Pottinger Novacat 352",
    "year": 2017,
    "hours": 2440,
    "hp": 63,
    "price": 6300,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 138,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Pottinger",
    "model": "Novacat 262",
    "name": "Pottinger Novacat 262",
    "year": 2022,
    "hours": 6732,
    "hp": 53,
    "price": 28900,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 139,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "New Holland",
    "model": "DiscCutter 313",
    "name": "New Holland DiscCutter 313",
    "year": 2020,
    "hours": 5503,
    "hp": 63,
    "price": 22800,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 140,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "New Holland",
    "model": "DiscCutter 442",
    "name": "New Holland DiscCutter 442",
    "year": 2017,
    "hours": 3957,
    "hp": 37,
    "price": 28500,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 141,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Kuhn",
    "model": "GMD 3125",
    "name": "Kuhn GMD 3125",
    "year": 2016,
    "hours": 1729,
    "hp": 45,
    "price": 11400,
    "country": "Belgium",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 142,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Kuhn",
    "model": "FC 3125 TLR",
    "name": "Kuhn FC 3125 TLR",
    "year": 2023,
    "hours": 8199,
    "hp": 82,
    "price": 26100,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 143,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Krone",
    "model": "EasyCut B 950",
    "name": "Krone EasyCut B 950",
    "year": 2018,
    "hours": 7938,
    "hp": 61,
    "price": 26700,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 144,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Krone",
    "model": "EasyCut F 320 CV",
    "name": "Krone EasyCut F 320 CV",
    "year": 2023,
    "hours": 3741,
    "hp": 58,
    "price": 24000,
    "country": "Poland",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 145,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Claas",
    "model": "Disco 3600",
    "name": "Claas Disco 3600",
    "year": 2016,
    "hours": 4852,
    "hp": 53,
    "price": 24700,
    "country": "Belgium",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 146,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Claas",
    "model": "Disco 8500",
    "name": "Claas Disco 8500",
    "year": 2023,
    "hours": 5228,
    "hp": 46,
    "price": 13600,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 147,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Pottinger",
    "model": "Novacat 352",
    "name": "Pottinger Novacat 352",
    "year": 2020,
    "hours": 4960,
    "hp": 63,
    "price": 26400,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 148,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "Pottinger",
    "model": "Novacat 262",
    "name": "Pottinger Novacat 262",
    "year": 2023,
    "hours": 1153,
    "hp": 81,
    "price": 6100,
    "country": "Poland",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 149,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "New Holland",
    "model": "DiscCutter 313",
    "name": "New Holland DiscCutter 313",
    "year": 2015,
    "hours": 4250,
    "hp": 57,
    "price": 4300,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 150,
    "category": "mowers",
    "categoryLabel": "Mowers",
    "brand": "New Holland",
    "model": "DiscCutter 442",
    "name": "New Holland DiscCutter 442",
    "year": 2018,
    "hours": 1159,
    "hp": 27,
    "price": 28600,
    "country": "Belgium",
    "image": "https://ik.imagekit.io/efarm/website/startpage_mower_7ca37102cf.jpg",
    "badge": null
  },
  {
    "id": 151,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kuhn",
    "model": "Vari-Master 153",
    "name": "Kuhn Vari-Master 153",
    "year": 2016,
    "hours": 7641,
    "hp": 173,
    "price": 22700,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 152,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kuhn",
    "model": "Multi-Master 123",
    "name": "Kuhn Multi-Master 123",
    "year": 2020,
    "hours": 5960,
    "hp": 180,
    "price": 27300,
    "country": "Italy",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 153,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Lemken",
    "model": "Juwel 8",
    "name": "Lemken Juwel 8",
    "year": 2020,
    "hours": 8617,
    "hp": 101,
    "price": 26100,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 154,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Lemken",
    "model": "Diamant 12",
    "name": "Lemken Diamant 12",
    "year": 2014,
    "hours": 7951,
    "hp": 162,
    "price": 40600,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 155,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kverneland",
    "model": "ES 100",
    "name": "Kverneland ES 100",
    "year": 2020,
    "hours": 8931,
    "hp": 142,
    "price": 12100,
    "country": "France",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 156,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kverneland",
    "model": "2500 S",
    "name": "Kverneland 2500 S",
    "year": 2020,
    "hours": 1388,
    "hp": 198,
    "price": 34800,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 157,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Vaderstad",
    "model": "Opus 500",
    "name": "Vaderstad Opus 500",
    "year": 2021,
    "hours": 1345,
    "hp": 219,
    "price": 37200,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 158,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Vaderstad",
    "model": "TopDown 500",
    "name": "Vaderstad TopDown 500",
    "year": 2021,
    "hours": 8441,
    "hp": 93,
    "price": 23400,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 159,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Amazone",
    "model": "Cayron 100",
    "name": "Amazone Cayron 100",
    "year": 2016,
    "hours": 5591,
    "hp": 215,
    "price": 20200,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 160,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Amazone",
    "model": "Cayros XM",
    "name": "Amazone Cayros XM",
    "year": 2017,
    "hours": 2358,
    "hp": 164,
    "price": 10600,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 161,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kuhn",
    "model": "Vari-Master 153",
    "name": "Kuhn Vari-Master 153",
    "year": 2018,
    "hours": 8837,
    "hp": 99,
    "price": 37200,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 162,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kuhn",
    "model": "Multi-Master 123",
    "name": "Kuhn Multi-Master 123",
    "year": 2017,
    "hours": 7983,
    "hp": 183,
    "price": 35400,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": "Exclusive"
  },
  {
    "id": 163,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Lemken",
    "model": "Juwel 8",
    "name": "Lemken Juwel 8",
    "year": 2016,
    "hours": 1643,
    "hp": 108,
    "price": 37800,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 164,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Lemken",
    "model": "Diamant 12",
    "name": "Lemken Diamant 12",
    "year": 2022,
    "hours": 4877,
    "hp": 166,
    "price": 26800,
    "country": "France",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 165,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kverneland",
    "model": "ES 100",
    "name": "Kverneland ES 100",
    "year": 2016,
    "hours": 7816,
    "hp": 136,
    "price": 36600,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 166,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kverneland",
    "model": "2500 S",
    "name": "Kverneland 2500 S",
    "year": 2022,
    "hours": 6680,
    "hp": 145,
    "price": 40700,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 167,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Vaderstad",
    "model": "Opus 500",
    "name": "Vaderstad Opus 500",
    "year": 2023,
    "hours": 6774,
    "hp": 108,
    "price": 20200,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 168,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Vaderstad",
    "model": "TopDown 500",
    "name": "Vaderstad TopDown 500",
    "year": 2019,
    "hours": 8249,
    "hp": 165,
    "price": 7400,
    "country": "Poland",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 169,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Amazone",
    "model": "Cayron 100",
    "name": "Amazone Cayron 100",
    "year": 2014,
    "hours": 2568,
    "hp": 98,
    "price": 37000,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 170,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Amazone",
    "model": "Cayros XM",
    "name": "Amazone Cayros XM",
    "year": 2021,
    "hours": 2133,
    "hp": 144,
    "price": 11100,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 171,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kuhn",
    "model": "Vari-Master 153",
    "name": "Kuhn Vari-Master 153",
    "year": 2020,
    "hours": 3029,
    "hp": 63,
    "price": 13900,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 172,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kuhn",
    "model": "Multi-Master 123",
    "name": "Kuhn Multi-Master 123",
    "year": 2023,
    "hours": 7012,
    "hp": 127,
    "price": 26700,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 173,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Lemken",
    "model": "Juwel 8",
    "name": "Lemken Juwel 8",
    "year": 2019,
    "hours": 8494,
    "hp": 196,
    "price": 29400,
    "country": "Ireland",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": "Hot Deal"
  },
  {
    "id": 174,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Lemken",
    "model": "Diamant 12",
    "name": "Lemken Diamant 12",
    "year": 2018,
    "hours": 4227,
    "hp": 77,
    "price": 19900,
    "country": "Germany",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 175,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kverneland",
    "model": "ES 100",
    "name": "Kverneland ES 100",
    "year": 2021,
    "hours": 3225,
    "hp": 85,
    "price": 11100,
    "country": "Spain",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 176,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Kverneland",
    "model": "2500 S",
    "name": "Kverneland 2500 S",
    "year": 2014,
    "hours": 5306,
    "hp": 71,
    "price": 25800,
    "country": "Italy",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 177,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Vaderstad",
    "model": "Opus 500",
    "name": "Vaderstad Opus 500",
    "year": 2022,
    "hours": 7251,
    "hp": 97,
    "price": 20500,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 178,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Vaderstad",
    "model": "TopDown 500",
    "name": "Vaderstad TopDown 500",
    "year": 2016,
    "hours": 1793,
    "hp": 106,
    "price": 15600,
    "country": "Austria",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 179,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Amazone",
    "model": "Cayron 100",
    "name": "Amazone Cayron 100",
    "year": 2021,
    "hours": 2844,
    "hp": 218,
    "price": 20300,
    "country": "Netherlands",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },
  {
    "id": 180,
    "category": "ploughs",
    "categoryLabel": "Ploughs",
    "brand": "Amazone",
    "model": "Cayros XM",
    "name": "Amazone Cayros XM",
    "year": 2018,
    "hours": 653,
    "hp": 125,
    "price": 34600,
    "country": "Denmark",
    "image": "https://ik.imagekit.io/efarm/website/plough_with_tractor_73477f794e.jpg",
    "badge": null
  },

  // Food & Beverages Category
  {
    "id": 181,
    "category": "food-beverages",
    "categoryLabel": "Food & Beverages",
    "brand": "Turkish Harvest",
    "model": "Extra Virgin Olive Oil",
    "name": "Premium Turkish Extra Virgin Olive Oil 5L",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 2400,
    "country": "Turkey",
    "image": "https://images.unsplash.com/photo-1474836762456-cbb2d3a9a5b5?w=500&h=400&fit=crop",
    "badge": "Fresh"
  },
  {
    "id": 182,
    "category": "food-beverages",
    "categoryLabel": "Food & Beverages",
    "brand": "Golden Grain Co.",
    "model": "Organic Wheat",
    "name": "Bulk Organic Wheat Grains - 25kg Bags",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 450,
    "country": "Ukraine",
    "image": "https://images.unsplash.com/photo-1585705481951-d0fdf677d86d?w=500&h=400&fit=crop",
    "badge": "Bulk"
  },
  {
    "id": 183,
    "category": "food-beverages",
    "categoryLabel": "Food & Beverages",
    "brand": "Sunflower Fields",
    "model": "Sunflower Oil",
    "name": "Refined Sunflower Oil - 20L Containers",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 1800,
    "country": "Ukraine",
    "image": "https://images.unsplash.com/photo-1599599810694-b5ac4dd93e12?w=500&h=400&fit=crop",
    "badge": null
  },
  {
    "id": 184,
    "category": "food-beverages",
    "categoryLabel": "Food & Beverages",
    "brand": "Spice Masters",
    "model": "Organic Spices Mix",
    "name": "Premium Organic Spices Collection",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 3200,
    "country": "India",
    "image": "https://images.unsplash.com/photo-1599599810611-b6efb6810599?w=500&h=400&fit=crop",
    "badge": "Premium"
  },

  // Raw Materials Category
  {
    "id": 185,
    "category": "raw-materials",
    "categoryLabel": "Raw Materials",
    "brand": "EcoWood Pellets",
    "model": "Premium Wood Pellets",
    "name": "Premium Wood Pellets 6MM - Bulk Supply",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 2800,
    "country": "Poland",
    "image": "https://images.unsplash.com/photo-1599599810739-52a73cf8b0e6?w=500&h=400&fit=crop",
    "badge": "Hot Deal"
  },
  {
    "id": 186,
    "category": "raw-materials",
    "categoryLabel": "Raw Materials",
    "brand": "Mineral Exports",
    "model": "Iron Ore",
    "name": "High-Grade Iron Ore - FOB Pricing",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 15000,
    "country": "Brazil",
    "image": "https://images.unsplash.com/photo-1599599810368-2c4be67b2407?w=500&h=400&fit=crop",
    "badge": null
  },
  {
    "id": 187,
    "category": "raw-materials",
    "categoryLabel": "Raw Materials",
    "brand": "Cotton Industries",
    "model": "Raw Cotton Fiber",
    "name": "Natural Raw Cotton - 500kg Bales",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 8500,
    "country": "India",
    "image": "https://images.unsplash.com/photo-1599599810920-5adc6ce3dd6a?w=500&h=400&fit=crop",
    "badge": null
  },
  {
    "id": 188,
    "category": "raw-materials",
    "categoryLabel": "Raw Materials",
    "brand": "Timber Trade",
    "model": "Sawn Lumber",
    "name": "European Sawn Timber - Grade A",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 5200,
    "country": "Germany",
    "image": "https://images.unsplash.com/photo-1599599810950-f8f7e9c3c0b0?w=500&h=400&fit=crop",
    "badge": "Exclusive"
  },

  // Industrial Supplies Category
  {
    "id": 189,
    "category": "industrial-supplies",
    "categoryLabel": "Industrial Supplies",
    "brand": "Steel Works",
    "model": "Carbon Steel Sheets",
    "name": "High-Quality Carbon Steel Sheets - Grade A",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 12000,
    "country": "Germany",
    "image": "https://images.unsplash.com/photo-1599599810825-e8c11e1c4b6f?w=500&h=400&fit=crop",
    "badge": null
  },
  {
    "id": 190,
    "category": "industrial-supplies",
    "categoryLabel": "Industrial Supplies",
    "brand": "Plastic Corp",
    "model": "HDPE Granules",
    "name": "Virgin HDPE Plastic Granules - 25kg Bags",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 3500,
    "country": "Saudi Arabia",
    "image": "https://images.unsplash.com/photo-1599599810658-e8f51cf83d7e?w=500&h=400&fit=crop",
    "badge": "Hot Deal"
  },
  {
    "id": 191,
    "category": "industrial-supplies",
    "categoryLabel": "Industrial Supplies",
    "brand": "Chemical Supplies",
    "model": "Industrial Lubricants",
    "name": "Premium Industrial Lubricating Oil - 200L Drums",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 4800,
    "country": "Netherlands",
    "image": "https://images.unsplash.com/photo-1599599810490-4cfccd0e0d45?w=500&h=400&fit=crop",
    "badge": null
  },
  {
    "id": 192,
    "category": "industrial-supplies",
    "categoryLabel": "Industrial Supplies",
    "brand": "Metal Fasteners",
    "model": "Industrial Bolts & Screws",
    "name": "Grade 8.8 Steel Fasteners - Bulk",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 2200,
    "country": "China",
    "image": "https://images.unsplash.com/photo-1599599810521-5b6f8b5b6c9d?w=500&h=400&fit=crop",
    "badge": null
  },

  // Global Network Category
  {
    "id": 193,
    "category": "global-network",
    "categoryLabel": "Global Network",
    "brand": "Premium Fresh",
    "model": "Fresh Vegetables Assortment",
    "name": "Certified Organic Fresh Vegetables - Mixed Selection",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 1200,
    "country": "Spain",
    "image": "https://images.unsplash.com/photo-1599599810152-7a8e3c8b3b3d?w=500&h=400&fit=crop",
    "badge": "Fresh"
  },
  {
    "id": 194,
    "category": "global-network",
    "categoryLabel": "Global Network",
    "brand": "Seafood Exports",
    "model": "Frozen Salmon Fillets",
    "name": "Premium Frozen Salmon Fillets - IQF Grade",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 6800,
    "country": "Norway",
    "image": "https://images.unsplash.com/photo-1599599810369-2c5b5f9b5b5b?w=500&h=400&fit=crop",
    "badge": "Premium"
  },
  {
    "id": 195,
    "category": "global-network",
    "categoryLabel": "Global Network",
    "brand": "Textile Masters",
    "model": "Polyester Fabric Rolls",
    "name": "High-Quality Polyester Fabric - 50-Meter Rolls",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 3600,
    "country": "Vietnam",
    "image": "https://images.unsplash.com/photo-1599599810180-2c5e5e5b5b5b?w=500&h=400&fit=crop",
    "badge": null
  },
  {
    "id": 196,
    "category": "global-network",
    "categoryLabel": "Global Network",
    "brand": "Energy Resources",
    "model": "Bitumen Grade 60/70",
    "name": "Bitumen for Road Construction - FOB",
    "year": 2024,
    "hours": 0,
    "hp": 0,
    "price": 8200,
    "country": "Iran",
    "image": "https://images.unsplash.com/photo-1599599810090-2c5e5e5b5b5b?w=500&h=400&fit=crop",
    "badge": "Bulk"
  }
];
